url: https://riteshmehrotra.github.io
baseurl: /kidzee-active-acorns/

# Site settings
title: Kidzee Sardardham | Active Acorns
email: admin@activeacorns.com
description: "A preschool with joyful learning environment where children explore, create, and grow holistically, nurturing their natural curiosity and fostering a lifelong love of learning."


# Team names, titles and social links
people:
- name: Yanki tandon
  pic: 1
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yanki-tandon-3b4a604/

- name: Ritesh Mehrotra
  pic: 2
  position: Strategy Consultant
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ritesh-mehrotra/



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/active.acorns/
  - title: facebook
    url: https://www.facebook.com/profile.php?id=61564934897714
 

# Postal address (add as many lines as necessary)
address:
  - line: A 102-A 105, Ganesh Pride, Khodiyar
  - line: Near Vaishnodevi Circle, S G Highway

# Build settings
markdown: kramdown
permalink: pretty